# 默认设置
default:
  groupCD: 500 # 群聊中所有指令操作冷却时间，单位毫秒,0则无限制
  singleCD: 2000 # 群聊中个人操作冷却时间，单位毫秒

  onlyReplyAt: 0 # 是否只仅关注主动@机器人的消息， 0-否 1-是 2-触发用户非主人只回复@机器人的消息及特定前缀的消息，主人免前缀
  botAlias:
    - 爱莉
    - 爱莉希雅
    - Elysia
    - elysia

  addLimit: 0 # 是否限制添加消息 0-所有群员 1-群管理员 2-主人
  addPrivate: 1 # 是否允许私聊添加
  addReply: 1 # 是否回复触发消息
  addAt: 0 # 是否提及触发用户
  addRecall: 60 # 是否撤回回复消息

  enable: []
  disable:
    - 禁用示例
    - 支持多个
    - 阿里云盘
    - 百度网盘
    - Markdown
    - 图片修复
    - 图片背景去除

# Bot单独设置
114514:default:
  onlyReplyAt: 1
  botAlias:
    - 爱莉
    - 爱莉希雅
    - Elysia
    - elysia

# 群单独设置
123456:
  groupCD: 500
  singleCD: 2000

# [Bot:群]单独设置
114514:123456:
  enable:
  disable:
929275476:
  __place__: 0
  groupCD: 500
  singleCD: 2000
  onlyReplyAt: 2
  botAlias:
    - 爱莉
    - 爱莉希雅
    - Elysia
    - elysia
  addLimit: 2
  addReply: 1
  addRecall: 60
  addPrivate: 1
  disable:
    - syjs:上下班

659945190:
  __place__: 0
  groupCD: 500
  singleCD: 2000
  onlyReplyAt: 2
  botAlias:
    - 爱莉
    - 爱莉希雅
    - Elysia
    - elysia
  addLimit: 2
  addReply: 1
  addRecall: 60
  addPrivate: 1
  disable:
    - syjs:上下班

554593924:
  __place__: 0
  groupCD: 500
  singleCD: 2000
  onlyReplyAt: 2
  botAlias:
    - 爱莉
    - 爱莉希雅
    - Elysia
    - elysia
  addLimit: 2
  addReply: 1
  addRecall: 60
  addPrivate: 1
  disable:
    - syjs:上下班

575663150:
  __place__: 0
  groupCD: 500
  singleCD: 2000
  onlyReplyAt: 2
  botAlias:
    - 爱莉
    - 爱莉希雅
    - Elysia
    - elysia
  addLimit: 2
  addReply: 1
  addRecall: 60
  addPrivate: 1
  disable:
    - syjs:上下班

158649349:
  __place__: 0
  groupCD: 500
  singleCD: 2000
  onlyReplyAt: 2
  botAlias:
    - 爱莉
    - 爱莉希雅
    - Elysia
    - elysia
  addLimit: 2
  addReply: 1
  addRecall: 60
  addPrivate: 1
  disable:
    - syjs:上下班

617703908:
  __place__: 0
  groupGlobalCD: 0
  singleCD: 1000
  onlyReplyAt: 2
  botAlias:
    - 爱莉
    - 爱莉希雅
    - elysia
    - Elysia
  imgAddLimit: 2
  imgMaxSize: 2
  addPrivate: 1
  disable:
    - syjs:上下班
